name: Deploy to multiple targets

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/gh-pages'
        run: |
          gh-pages -d build

      # When the dist_dir is ready, deploy it to neocities
      - name: Deploy to neocities
        if: github.ref == 'refs/heads/gh-pages'
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          dist_dir: .  # Change to the directory where your build artifacts are stored
